### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-manage#15]
Currently, the stderr/stdout for a system is buried away inside the `data_dir` for a node. When a script fails, the only way to get any further debugging/verbosity is to manually read that file.

What would be useful is some sort of verbose/debug/errors flag for `manage node show` to provide this information alongside the current node state
```
[centos@gateway1(cluster) ~]$ /opt/flight/bin/flight manage node show
Showing current state of hostname: gateway1

job1: FAIL

# Verbose
[centos@gateway1(cluster) ~]$ /opt/flight/bin/flight manage node show --verbose
Showing current state of hostname: gateway1

job1: FAIL
stdout:
  this is a line of stdout
  this is another
stderr:
  error: forgot to exit with 0

# Errors
[centos@gateway1(cluster) ~]$ /opt/flight/bin/flight manage node show --errors
Showing current state of hostname: gateway1

job1: FAIL
stderr:
  error: forgot to exit with 0
```

**Comment by VoxSecundus** [comment]
Would you prefer both an --errors AND --verbose flag to be added, or just one that displays all error data?

**Comment by ColonelPanics** [comment]
I think, like the example, it could be beneficial to have a verbose option for all output (stdout and stderr) and error option just for stderr
