### ISSUE TITLE
Script Location Unclear

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-manage#2]
After installation I was unable to determine _where_ I should be putting scripts for inclusion with the tool. I was only able to work this out by looking through the code:

https://github.com/openflighthpc/flight-manage/blob/fb749b3600f10ffb1b404170e7cb8883e475b80e/lib/flight-manage/config.rb#L59

I think it needs to be clearer (separate of documentation) as to where scripts should be placed. A couple of thoughts on improving this:
- Show the directory being searched in the `manage script list` output
- Create a default config file (more thoughts on that at #3 )

**Comment by DavidMarchant** [comment]
Yes, I agree, so far I have been developing this with the same inclinations as in inventoryware - that the storage system will be opaque to the users of the program. However as users will actually often want to interact with the scripts during use I'll leave info as to where everything is. 
So for 1) yes I'll add that output
I'll place my reply on 2) on #3
