### ISSUE TITLE
Stdout/stderr indentation

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-manage#23]
The output for stdout/stderr in the `--verbose`/`--error` output for `node show` seems to incorrectly indent
```
[root@metalcontroller manage]# /opt/flight/bin/bundle exec bin/manage node show --verbose
Showing current state of hostname: metalcontroller

stu2: FAIL
stdout:
  Starting sleep of death
Done, time to die!
stderr:
```

I'd expect every line to be indented by at least the display indent.

See how the file shows the stdout in the managedata:
```
[root@metalcontroller manage]# cat /opt/service/flight/managedata/metalcontroller.yaml
---
stu2:
  time: '2019-09-05T11:58:26+00:00'
  status: FAIL
  exit_code: 1
  stdout: |-
    Starting sleep of death
    Done, time to die!
  stderr: ''
```

**Comment by VoxSecundus** [comment]
I'm assuming that new lines should only be preserved if the `|-` bit is used?

**Comment by ColonelPanics** [comment]
@VoxSecundus I think so, not sure of the exact YAML syntax off the top of my head!
