### ISSUE TITLE
Report improvements

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-manage#24]
The current report layout is shaping up nicely. On a rethink it's probably worth making some optimisations to:
- Reduce screen width used (as many scripts/nodes are likely to be the case)
- Allow filtering of results

## Reduce screen width

To better reduce the width used by the vertical column it's probably worth using double depth on the rows. Increasing the height isn't as much concern as wrapping issues that will arise with using width.

For example:
```
+--------+---------+--------+
| Node   | Script  | Status |
+--------+---------+--------+
| node01                    |
+--------+---------+--------+
|        | script1 |   OK   |
+--------+---------+--------+
|        | script2 |   OK   |
+--------+---------+--------+
|        | script3 |  FAIL  |
+--------+---------+--------+
| node02                    |
+--------+---------+--------+
|        | script1 |   OK   |
+--------+---------+--------+
|        | script2 |   OK   |
+--------+---------+--------+
|        | script3 |  N/A   |
+--------+---------+--------+
```

Not married to how cells merge or anything, but a general gist to show the rough idea.

_It's worth noting that this allows for better displaying of node-specific scripts as there won't be a need for all nodes to have that column (as with previous iterations)._

## Filter arguments

The current report table look would still lend itself useful to filtered reports (as long as there are suitable measures for dealing with width). 

Possible filters would be in line with filters that are currently available in other commands:
- `-r, --role`
- `-s, --stage`
- `-n, --node` (noted that there may be some overlap with what `node show` does, but that's okay as the CLI is needing a bit of a restructure/reformat and `node show` still has useful debug elements which are outside the scope of `report`)
- `-c,--chain` (although I haven't touched "chains" for a while so might be outside of scope for a simpler table)

**Comment by VoxSecundus** [comment]
Currently have the table output as the following; I know you said you aren't worried about the cell merging, but still worth a look before I commit
```
+------------+--------+--------+
| Node       | Script | Status |
+------------+--------+--------+
| metal      |        |        |
|            | test   | N/A    |
|            | test2  | N/A    |
|            | test3  | N/A    |
| jack-alces |        |        |
|            | test   | N/A    |
|            | test2  | FAIL   |
|            | test3  | N/A    |
+------------+--------+--------+
```

**Comment by ColonelPanics** [comment]
Looking great!! Definitely have a look at merging and stuff but what you've got there is 👌

**Comment by VoxSecundus** [comment]
Sweet, since both dev/verbose and dev/report only need enhancements now I'll merge them both into develop.
