### ISSUE TITLE
Improve Command Line

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-manage#26]
The CLI structure doesn't make too much sense considering that `node` is pretty much empty and that the script command can also run multiple scripts.

Refactor the command line to have different entrypoints:

- `run` for executing scripts
- `list` with either a node or scripts subcommand
- `show` with either a node or scripts subcommand
- `report` for displaying the full script/node info
- `resolve` 
- `import` 

Above is rough thought on the structure, actual refactor may end up differently, just try and structure it in a bit more of a sensible way!

**Comment by VoxSecundus** [comment]
Figured the structure you gave was a fairly good model to follow, so the CLI has been refactored to that specification.
