### ISSUE TITLE
Handling whitespace in script names

### ISSUE THREAD

**Issue by VoxSecundus** [openflighthpc/flight-manage#27]
When running a script that has whitespace in its filename, the result of the script running is always:
```
test (copy 1):
  time: '2019-09-16T11:09:18+01:00'
  status: FAIL
  exit_code: 1
  stdout: ''
  stderr: |-
    sh: -c: line 0: syntax error near unexpected token `('
    sh: -c: line 0: `bash /opt/service/scripts/test (copy 1).bash'
```

Is this something that should be handled (i.e. adding quotes around the name), or prevented (telling the user that scripts must not include whitespace (or any escapable character for that matter))?

**Comment by ColonelPanics** [comment]
I'd lean towards the latter. We can get lost spending too much time cleaning/handling filenames. Instead check if it's alphanumeric + `.`, otherwise throw an error or warning at the user
