### ISSUE TITLE
Default Config File

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-manage#3]
Without looking into the codebase it is unclear that there are config values that can be overridden in `etc/manage.conf`. 

I propose that `etc/manage.conf` should exist in the repo and contain the defaults that are fallen back to in `config.rb`

https://github.com/openflighthpc/flight-manage/blob/fb749b3600f10ffb1b404170e7cb8883e475b80e/lib/flight-manage/config.rb#L51-L60

What are your thoughts on this?

**Comment by DavidMarchant** [comment]
Yep, as with #2 I feel that there's no reason not to implement this increased transparency
