### ISSUE TITLE
Run Stage Error

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-manage#4]
How come this script isn't run as part of the `oneoff` stage run? I haven't specified a role for the script so I presume it'd work?

```
[root@headnode1 [Headnode] ~]# flight manage script list
anotherscript/run.bash - A super slow script
configure-a-thing/configureitall.bash - Install a package that's critical
script-without-role/runit.bash - Touch some files
testscript1/bar.bash - Touch a file in /tmp/
[root@headnode1 [Headnode] ~]# cat /opt/service/scripts/script-without-role/runit.bash
#!/bin/bash
#FLIGHTstage: oneoff
#FLIGHTrerunnable: false
#FLIGHTdescription: Touch some files

sleep 10
uptime
[root@headnode1 [Headnode] ~]# flight manage script run -s oneoff
flight manage: No scripts found with no role and stage 'oneoff'
```

**Comment by ColonelPanics** [comment]
Okay this seems to be because of `stage` and not `stages` being the variable. Changing this allowed the script to execute. (thanks @DavidMarchant )

**Comment by DavidMarchant** [comment]
Yeah, just to note - there's some contention to be had with `role/stage` vs `roles/stages` but considering a comma-separated list of strings is valid for both the plural is to be preferred. This is a deviation from the requirements however, which specifies `roles` and `stage`.
