### ISSUE TITLE
Handle scripts not being executable

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-manage#8]
Currently a script will need to be executable for `flight-manage` to run it. As we're enforcing `.bash` extensions could we just execute the scripts as `bash script.bash` instead of using a method of running that requires the script to be executable?

**Comment by DavidMarchant** [comment]
Fixed in https://github.com/openflighthpc/flight-manage/commit/d742d8298cc71e5d4f3092607d386b60dcd1a35b
